
service: burninator-backend
provider:
  name: aws
  runtime: rust
  memorySize: 128
  stage: prod
  region: us-west-1


package:
  individually: true

plugins:
  - serverless-rust

functions:
  graphql:
    handler: burninator-service
    events:
      - http:
          path: '/graphql'
          method: GET
      - http:
          path: '/graphql'
          method: POST

